package me.travja.performances.api.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.*;
import me.travja.performances.serializers.PersonDeserializer;
import me.travja.performances.serializers.PersonSerializer;
import me.travja.performances.serializers.ZonedDateTimeDeserializer;
import me.travja.performances.serializers.ZonedDateTimeSerializer;

import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.UUID;

@Data
@DynamoDBDocument
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Audition")
public class Audition {

    @Getter(AccessLevel.PRIVATE)
    @Setter(AccessLevel.PRIVATE)
    private static DateTimeFormatter format = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss O");
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    private        UUID              id;
    @DynamoDBAttribute(attributeName = "performer")
    @JsonSerialize(using = PersonSerializer.class)
    @JsonDeserialize(using = PersonDeserializer.class)
    private        Performer         performer;
    @DynamoDBAttribute(attributeName = "date")
    @JsonSerialize(using = ZonedDateTimeSerializer.class)
    @JsonDeserialize(using = ZonedDateTimeDeserializer.class)
    @DynamoDBTypeConverted(converter = DateTimeConverter.class)
    private        ZonedDateTime     date;
    @DynamoDBAttribute(attributeName = "status")
    private        String            status = "Waiting";

    public Audition(Performer performer, ZonedDateTime date) {
        this.performer = performer;
        this.date = date;
    }

}
